# Generated by Django 2.2 on 2020-04-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
